### ISSUE TITLE
Terrestrial Enlightenment Charms not available

### ISSUE THREAD

**Issue by Caveat-zz** [anathema/anathema#200]
Current behavior: These Charms are tagged Celestial, making Dragon-Blooded (other than Immaculate Martial Artists) unable to select them.

Expected behavior: These Charms would be tagged Terrestrial, & a Dragon-Blooded with one of the Terrestrial-level Charms with the Enlightenment keyword would be able to select Celestial Martial Arts Charms.

All of the Dragon-Blooded are supposed to be able to take the "Enlightenment" keyword Charms in the "Terrestrial Initiations into Celestial Martial Arts" cascade (the last option on the Martial Arts drop-down list). If a Dragon-Blooded has any of these Enlightenment Charms they can select Celestial Martial Arts Charms.

**Comment by apturtia** [comment]
Hi,

My players just noticed that the Outcaste DBs can not get the Terrestrial Initiations into Celestial Martial Arts charms. We had concluded during game planing session that they want to make MA characters and they have just barely enough bonus points to get CMA Outcaste. Page 95 in MoEP:DB states that "If (and only if) a character has ﬁve dots in the Mentor Background (to represent a rogue monk or one of the Celestial Exalted who is willing to train him), the character may begin the game with Immaculate Martial Arts Charms."

I know it's a bit late considering the upcoming 3rd ed, but could this be patched?

BR, Petteri

**Comment by UrsKR** [comment]
Hi, @apturtia, I never noticed that line. 
I am sorry that Anathema doesn't support this specific scenario, and we have stopped working on 2e stuff a while ago.
You could trick the system by creating your characters, making them experienced and immediately giving them bonus XP to buy the Charms that should rightfully be theirs at character creation.

Does this help?
Urs

**Comment by apturtia** [comment]
Thanks for a quick response. We can certainly use that trick! 
I know you do great work with the 3rd edition.
- Petteri
